sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0e2bb872ecdd_key -iv $encrypted_0e2bb872ecdd_iv -in service-account.json.enc -out /app/service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json